version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/raw
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
      timeout: 30
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 60
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 30
